### ISSUE TITLE
Embark issues

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-ecosystem#36]
Tracking thread about issues in other crates & open source projects that we've filed or run into and commented on. Linking them here makes it easier for us to see our overall list of outstanding issues. 

This is specifically for issues. PRs we track in gfx-rs/naga#20. 

We use this for specific concrete issues, while the individual and usually larger open ecosystem challenges/wants/needs we track as separate high-level issues in this repo.

**Comment by Jake-Shadle** [comment]
- [ ] [`dependabot:` Update to Rust 1.37.0](https://github.com/dependabot/feedback/issues/650)

Dependabot is using an older version of cargo which doesn't support the `default-run` key, breaking the dependency update.

**Comment by repi** [comment]
- [`chrono:` Feature flag for the new wasm javascript support?](https://github.com/chronotope/chrono/issues/334)

Staying on `chrono` 0.4.7 until this have been resolved as the wasm javascript dependencies do not work for us as we run wasm outside of a browser

**Comment by hrydgard** [comment]
- [ ] [`tower-grpc` Building multiple protos as clients together doesn't work](https://github.com/tower-rs/tower-grpc/issues/204)

Working around this for now by putting one of the protos in a different package.

**Comment by repi** [comment]
- [ ] [`glam:` Missing serialization support for Mat2/Mat3/Mat4](https://github.com/bitshifter/glam-rs/issues/17)

**Comment by hrydgard** [comment]
- [ ] [`minifb` Windows: OBS can't capture minifb windows at other scales than 100%](https://github.com/emoon/minifb/issues/26)

**Comment by hrydgard** [comment]
- [ ] [`tract` no_panic attribute applied to function that can panic (SafePatchIterator::next(), I think)](https://github.com/snipsco/tract/issues/167)

**Comment by h3r2tic** [comment]
- [ ] [`wasmer`: Add support for stack traces from wasm](https://github.com/wasmerio/wasmer/issues/827)

**Comment by repi** [comment]
- [ ] [`gltf` Publish 0.14 release?](https://github.com/gltf-rs/gltf/issues/253)

**Comment by repi** [comment]
- [ ] [`actions-rs` Auto rustfmt commit action?](https://github.com/actions-rs/meta/issues/8)

**Comment by hrydgard** [comment]
- [ ] tract: https://github.com/snipsco/tract/issues/173

**Comment by Jake-Shadle** [comment]
- [ ] [`ring` Make license info machine readable](https://github.com/briansmith/ring/issues/902)

**Comment by repi** [comment]
- [ ] [`anyhow` Add ensure macro?](https://github.com/dtolnay/anyhow/issues/1)

**Comment by repi** [comment]
- [ ] [`sentry` anyhow integration](https://github.com/getsentry/sentry-rust/issues/162)

**Comment by MaikKlein** [comment]
- [ ] [`anyhow` Is it possible to go back to an `Box<dny Error>`? ](https://github.com/dtolnay/anyhow/issues/10)

**Comment by hrydgard** [comment]
- [ ] ```tract``` [Missing node type: AddV2](https://github.com/snipsco/tract/issues/180)

**Comment by repi** [comment]
- [ ] [`mio-extra` Publish new version to crates.io?](https://github.com/dimbleby/mio-extras/issues/4)

**Comment by repi** [comment]
- [ ] [`sentry-types` Upgrade url from 1.7 -> 2.0](https://github.com/getsentry/rust-sentry-types/issues/39)

**Comment by MaikKlein** [comment]
- [ ] [Static variables are not exported in wasm](https://github.com/rust-lang/rust/issues/67453)

**Comment by repi** [comment]
- [ ] [`tonic` UDS example does not build on Windows](https://github.com/hyperium/tonic/issues/205)

**Comment by repi** [comment]
- [ ] [`keccak` Relicense from CC0 to  MIT/Apache-2.0?](https://github.com/RustCrypto/sponges/issues/5)

**Comment by MaikKlein** [comment]
- [ ] [HiDpiMode::Default does not use the DPI factor from winit](https://github.com/Gekkio/imgui-rs/issues/288)

**Comment by repi** [comment]
- [ ] [`shaderc` Remove GlslangInitializer mutex lock?](https://github.com/google/shaderc/issues/945)

**Comment by hrydgard** [comment]
- [ ] [`cranelift` Windows (Fastcall) calling convention: Callee-saved XMM (FP) registers are not actually saved](https://github.com/bytecodealliance/cranelift/issues/1366)

**Comment by hrydgard** [comment]
- [ ] [`wasmer` Heads up about serious bug in Cranelift (Windows)](https://github.com/wasmerio/wasmer/issues/1179)

**Comment by hrydgard** [comment]
- [ ] [`wasmer` "Illegal instruction" error the second time a panic is caught (Windows-only?) ](https://github.com/wasmerio/wasmer/issues/1204)

**Comment by Jake-Shadle** [comment]
- [ ] [`wasmer` Panic hooks stop working after 2nd panic](https://github.com/wasmerio/wasmer/issues/1333)

**Comment by hrydgard** [comment]
- [ ] [`rust-clippy` Integer division lint should allow non-zero constant denominators](https://github.com/rust-lang/rust-clippy/issues/5391)

**Comment by repi** [comment]
- [ ] [`wayland-rs` Replace xcur GPL-3.0 dependency?](https://github.com/Smithay/wayland-rs/issues/319)

**Comment by repi** [comment]
- [ ] [`glam` Alternate Vec3 that's actually 12 byte](https://github.com/bitshifter/glam-rs/issues/36)

**Comment by Jake-Shadle** [comment]
- [ ] [`sentry` Panic + deadlock on Unix with LLD 10](https://github.com/getsentry/sentry-rust/issues/220)

**Comment by repi** [comment]
- [ ] [`gfx-portability` Static linking support?](https://github.com/gfx-rs/portability/issues/214)

**Comment by emilk** [comment]
[ ] [`imgui-rs` Modifier keys always false on winit + mac](https://github.com/Gekkio/imgui-rs/issues/329)

**Comment by hrydgard** [comment]
- [ ] [`winapi` Missing: WTS session APIs](https://github.com/retep998/winapi-rs/issues/902)

**Comment by VZout** [comment]
- [ ] [`winit` [Windows] Dialogs and message boxes causes crash](https://github.com/rust-windowing/winit/issues/1602)

**Comment by MaikKlein** [comment]
- [ ] [`moltenvk` Undefined symbol `___isPlatformVersionAtLeast` while linking with libmoltenvk.a](https://github.com/KhronosGroup/MoltenVK/issues/913)

**Comment by VZout** [comment]
- [ ] [`winit` [Android] Run return](https://github.com/rust-windowing/winit/issues/1603)

**Comment by repi** [comment]
- [ ] [`rust-analyzer` Gracefully handle "Rust file outside current workspace is not supported yet" ](https://github.com/rust-analyzer/rust-analyzer/issues/4859)

**Comment by hrydgard** [comment]
- [ ] `steamvr` [Required Vulkan extensions list needs adjustment] (https://steamcommunity.com/app/250820/discussions/8/2448217320137020268/)

**Comment by VZout** [comment]
[ ] [`app-dirs2` Android support](https://github.com/app-dirs-rs/app_dirs2/issues/3)

**Comment by repi** [comment]
- [ ] [`tokei` Markdown language detection with "rust,ignore" mdbook syntax?](https://github.com/XAMPPRocky/tokei/issues/569)

**Comment by repi** [comment]
- [ ] [`flexbuffers` Flexbuffers support for u128?](https://github.com/google/flatbuffers/issues/6002)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`cargo apk` Publish a new release](https://github.com/rust-windowing/android-ndk-rs/issues/44)

**Comment by repi** [comment]
- [ ] [`wasmer` Cranelift backend support for ARM on Android (and Mac)](https://github.com/wasmerio/wasmer/issues/1495)

**Comment by VZout** [comment]
* [ ] [`winit` Opening a dialog crashes the application](https://github.com/rust-windowing/winit/issues/1685)

**Comment by repi** [comment]
- [ ] [`imgui-inspect` Upgrade to imgui 0.5?](https://github.com/aclysma/imgui-inspect.git)

**Comment by khyperia** [comment]
- [ ] [`clspv` Segfault when compiling constant structs with pointers to constant structs](https://github.com/google/clspv/issues/631)
- [ ] [`SPIRV-LLVM-Translator` Incorrect spir-v generated when compiling constant structs with pointers to constant structs](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/729)
- [ ] [`SPIRV-LLVM-Translator` Crash on struct OpAccessChain with non-32-bit integer index](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/754)
- [ ] [`SPIRV-Tools` spirv-opt ssa-rewrite produces code that fails the validator](https://github.com/KhronosGroup/SPIRV-Tools/issues/3873)

**Comment by repi** [comment]
- [ ] [`cargo-supply-chain` Faster crates.io fetching?](https://github.com/rust-secure-code/cargo-supply-chain/issues/8)

**Comment by XAMPPRocky** [comment]
- [ ] [Tracking Issue for -Z codegen-backend](https://github.com/rust-lang/rust/issues/77933)

**Comment by khyperia** [comment]
- [ ] [`cargo` Output filename collision with dylib on windows release mode](https://github.com/rust-lang/cargo/issues/8794)

**Comment by maxded** [comment]
- [ ] [`wasmtime` Add cargo deny](https://github.com/bytecodealliance/wasmtime/issues/2225)

**Comment by repi** [comment]
- [ ] [`naga` [spv-in] Embark SPIRV shaders fail to parse with multiple errors](https://github.com/gfx-rs/naga/issues/243)

**Comment by khyperia** [comment]
- [ ] [`cargo` fingerprint.rs uses different target roots when serializing/deserializing ](https://github.com/rust-lang/cargo/issues/8817)

**Comment by termhn** [comment]
- [ ] [`glam` field accessor ergonomics for shaders/non-simd paths](https://github.com/bitshifter/glam-rs/issues/89)

**Comment by XAMPPRocky** [comment]
- [ ] [Add Library API](https://github.com/DianaNites/cargo-sysroot/issues/4)

**Comment by maxded** [comment]
- [ ] [ `winit` Feature: bring window to top](https://github.com/rust-windowing/winit/issues/1750)

**Comment by hrydgard** [comment]
- [ ] [`rust-analyzer` Unresolved import for SIMD types](https://github.com/rust-analyzer/rust-analyzer/issues/6556)

**Comment by repi** [comment]
- [ ] [`tract` Support for aarch64-apple-darwin target?](https://github.com/sonos/tract/issues/406)

**Comment by repi** [comment]
- [ ] [`prost` Bundled Mac aarch64 binary support](https://github.com/danburkert/prost/issues/393)

**Comment by repi** [comment]
- [ ] [`tonic` Odd 240 second stalls in tonic client after each batch of ~100 requests](https://github.com/hyperium/tonic/issues/494)

**Comment by XAMPPRocky** [comment]
- [ ] [`rspirv` Update derive_more dependency](https://github.com/gfx-rs/rspirv/issues/172)

**Comment by Jake-Shadle** [comment]
- [ ] [`wasmtime` Consider adding support for MacOS exception ports](https://github.com/bytecodealliance/wasmtime/issues/2456)

**Comment by davidpdrsn** [comment]
- [ ] [How to test that `PubsubConnection` is still working?](https://github.com/benashford/redis-async-rs/issues/62)

**Comment by hrydgard** [comment]
- [ ] [`gpu-allocator` VulkanAllocator not movable](https://github.com/Traverse-Research/gpu-allocator/issues/10)

**Comment by MaikKlein** [comment]
- [ ] [`rust-analyzer` No completion for impl blocks on dyn traits](https://github.com/rust-analyzer/rust-analyzer/issues/6777)

**Comment by hrydgard** [comment]
- [ ] [`rust-analyzer` "Failed to parse macro invocation" when using puffin (regression)](https://github.com/rust-analyzer/rust-analyzer/issues/6811)

**Comment by davidpdrsn** [comment]
- [ ] [`clippy` New lint: Implement From instead of Into](https://github.com/rust-lang/rust-clippy/issues/6456)

**Comment by emilk** [comment]
* [ ] [`parking_lot_core` wasm link issue](https://github.com/Amanieu/parking_lot/issues/269)

**Comment by repi** [comment]
- [ ] [`mimallocator` Maintenance status of this crate?](https://github.com/gnzlbg/mimallocator/issues/9)
- [ ] [`mimallocator` Support building for aarch64-apple-darwin target](https://github.com/gnzlbg/mimallocator/issues/10)

**Comment by VZout** [comment]
* [ ] [`spirv-cross` Name fixup is undone by `replace_illegal_names` in the case of entry points](https://github.com/KhronosGroup/SPIRV-Cross/issues/1571)

**Comment by VZout** [comment]
* [ ] [`spirv-cross` MSL: Duplicate built-in variables with multiple entry points.](https://github.com/KhronosGroup/SPIRV-Cross/issues/1580)

**Comment by davidpdrsn** [comment]
* [ ] [`tonic` Follow redirects in client](https://github.com/hyperium/tonic/issues/528)

**Comment by davidpdrsn** [comment]
- [ ] [`redis-async` Make Tokio 1.0 the default?](https://github.com/benashford/redis-async-rs/issues/66)

**Comment by repi** [comment]
- [ ] [`wasmtime-runtime` Wasmtime trap handler doesn't build on latest libc 0.2.82 for aarch64-apple-darwin](https://github.com/bytecodealliance/wasmtime/issues/2575)

**Comment by emilk** [comment]
* [ ] [`rapier`: Simple pendulum explodes](https://github.com/dimforge/rapier/issues/86) - an issue I found while evaluating `rapier`.

**Comment by VZout** [comment]
* [ ] [`MoltenVK` SPIRVReflection: Multiple entry point support for getShaderOutputs](https://github.com/KhronosGroup/MoltenVK/pull/1204)

**Comment by davidpdrsn** [comment]
- [ ] [`rust-analyzer`: Chokes on type with nested `impl Trait`s](https://github.com/rust-analyzer/rust-analyzer/issues/7403)

**Comment by emilk** [comment]
* [ ] [`rapier: Collision bug`](https://github.com/dimforge/rapier/issues/96)

**Comment by hrydgard** [comment]
- [ ] [`rust-analyzer` "could not resolve macro 'm'" when macro imported into function directly](https://github.com/rust-analyzer/rust-analyzer/issues/7437)

**Comment by Jake-Shadle** [comment]
- [ ] [`mimalloc` Remove CMake dependency](https://github.com/purpleprotocol/mimalloc_rust/issues/51)

**Comment by VZout** [comment]
* [ ] [`sccache` Compiler mismatch when using rust-toolchain file](https://github.com/mozilla/sccache/issues/943)

**Comment by emilk** [comment]
* [ ] [`rapier`: 64-bit handles](https://github.com/dimforge/rapier/issues/110)

**Comment by emilk** [comment]
* [x] [`rapier`: energy conservation bug](https://github.com/dimforge/rapier/issues/97)

**Comment by emilk** [comment]
* [ ] [`clippy: suspicious-operation-groupings` false positive](https://github.com/rust-lang/rust-clippy/issues/6722)

**Comment by MaikKlein** [comment]
- [ ] [`rust-analyzer` No completions for impl blocks on dyn traits with lifetimes](https://github.com/rust-analyzer/rust-analyzer/issues/7683)

**Comment by emilk** [comment]
* [ ] [`rust-analyzer`: unresolved-module in rapier repository](https://github.com/rust-analyzer/rust-analyzer/issues/7715)

**Comment by emilk** [comment]
* [x] [`glam`: Add `Quaternion::inverse()`](https://github.com/bitshifter/glam-rs/issues/131)

**Comment by khyperia** [comment]
* [ ] [`Vulkan-ValidationLayers`: "Push constant is used in .... But ... doesn't set ..." incorrectly reported for modules with multiple entry points](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2583)

**Comment by emilk** [comment]
* [ ] [`glam`: RFC for a point type](https://github.com/bitshifter/glam-rs/issues/133)

**Comment by emilk** [comment]
* [ ] [`rapier`: modify existing joints](https://github.com/dimforge/rapier/issues/121)

**Comment by eddyb** [comment]
* [ ] [`SPIRV-Cross` [MSL] C pointer type syntax is not (trivially) concatenable, like SPIRV-Cross assumes.](https://github.com/KhronosGroup/SPIRV-Cross/issues/1628)

**Comment by emilk** [comment]
* [ ] [`rapier`: joint motor stability](https://github.com/dimforge/rapier/issues/125)

**Comment by emilk** [comment]
* [ ] [`glam`: `PartialOrd` gotchas](https://github.com/bitshifter/glam-rs/issues/138)

**Comment by emilk** [comment]
* [ ] [`rapier`: per-collider mass properties](https://github.com/dimforge/rapier/issues/132)

**Comment by emilk** [comment]
* [ ] [`parry`: compute trimesh mass properties](https://github.com/dimforge/parry/issues/16) (parry is the geometry-crate of rapier)

**Comment by repi** [comment]
- [ ] [`clippy` wildcard_enum_match_arm fail with non-exhaustive enums and OR patterns](https://github.com/rust-lang/rust-clippy/issues/6862)

**Comment by hrydgard** [comment]
- [ ] [`glam` ".fract" in vector types](https://github.com/bitshifter/glam-rs/issues/144)

**Comment by emilk** [comment]
* [ ] [`clippy`: CLI false positive deprecation warning](https://github.com/rust-lang/rust-clippy/issues/6879)

**Comment by emilk** [comment]
* [ ] [`rapier`: velocity iteration fidelity control](https://github.com/dimforge/rapier/issues/152)

**Comment by repi** [comment]
- [`rkyv` Comparing enum with archived enum?](https://github.com/djkoloski/rkyv/issues/68)

**Comment by XAMPPRocky** [comment]
- [ ] [`cargo` Undefined symbols for x86_64 when using resolver="2"](https://github.com/rust-lang/cargo/issues/9278)

**Comment by repi** [comment]
- [ ] [`clippy`  string_lit_as_bytes should also detect `"str".to_string().into_bytes()`](https://github.com/rust-lang/rust-clippy/issues/6927)

**Comment by lpil** [comment]
- [ ] [`mockito`  Release new version with latest fixes](https://github.com/lipanski/mockito/issues/138)

**Comment by khyperia** [comment]
- [ ] [`Vulkan-ValidationLayers`  Segfault in RunUsedStruct with two push constants](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2646)

**Comment by XAMPPRocky** [comment]
- [ ] [`rust-lang/compiler-team` Rename -Cllvm-args to something backend agnostic](https://github.com/rust-lang/compiler-team/issues/421)

**Comment by XAMPPRocky** [comment]
- [ ] [`rust-lang/clippy` Lint on large `std::{include_str!, include_bytes!};` calls.](https://github.com/rust-lang/rust-clippy/issues/7005)

**Comment by XAMPPRocky** [comment]
- [ ] [`rust-lang/rustup` Components occasionally become corrupted after rustup upgrade](https://github.com/rust-lang/rustup/issues/2704)

**Comment by MaikKlein** [comment]
- [ ] [`rust-lang/rustc` Unknown imports appear randomly in wasm with wasm32-unknown-unknown](https://github.com/rust-lang/rust/issues/83604)

**Comment by XAMPPRocky** [comment]
- [ ] [`glam` New crates.io release](https://github.com/bitshifter/glam-rs/issues/161)

**Comment by emilk** [comment]
* [`rapier`: prismatic motor bug](https://github.com/dimforge/rapier/issues/172)

**Comment by repi** [comment]
- [`agones` Make a rust SDK crate](https://github.com/googleforgames/agones/issues/1932)

**Comment by hrydgard** [comment]
- [ ] [`rust-analyzer` #[cfg] attrs in destructuring assignments are erroneously detected as syntax errors](https://github.com/rust-analyzer/rust-analyzer/issues/8608)

**Comment by khyperia** [comment]
- [ ] [`naga` gl_VertexIndex & 2 causes naga validation failure](https://github.com/gfx-rs/naga/issues/745)

**Comment by XAMPPRocky** [comment]
- [ ] [`rspirv` New spirv_headers release](https://github.com/gfx-rs/rspirv/issues/191)
- [ ] [`rspirv` `ImageFormat::Rgb10a2ui` uses inconsistent casing.](https://github.com/gfx-rs/rspirv/issues/191)

**Comment by davidpdrsn** [comment]
- [ ] [`tracing` Duplicate span fields when using tracing-appender and `Span::record`](https://github.com/tokio-rs/tracing/issues/1372)

**Comment by XAMPPRocky** [comment]
- [ ] [Index out of bounds when running `cargo doc` in `rustc_metadata/src/creader.rs`](https://github.com/rust-lang/rust/issues/84738)

**Comment by khyperia** [comment]
- [ ] [`SPIRV-Tools` strip-reflect removes OpString, but not OpLine referencing it](https://github.com/KhronosGroup/SPIRV-Tools/issues/4269)

**Comment by repi** [comment]
- [ ] [`liquid-core` anymap dependency is unmaintained (RUSTSEC-2021-0065)](https://github.com/cobalt-org/liquid-rust/issues/440)

**Comment by davidpdrsn** [comment]
- [ ] [`cargo` `check --tests` always succeeds if you have `test = false` in Cargo.toml](https://github.com/rust-lang/cargo/issues/9536)

**Comment by davidpdrsn** [comment]
- [ ] [`rust-analyzer` `expandMacro` doesn't work if cursor is on first letter](https://github.com/rust-analyzer/rust-analyzer/issues/9366)

**Comment by Jake-Shadle** [comment]
- [ ] [`rust` New ICE in 1.55.0-nightly 6d820866a 2021-06-29](https://github.com/rust-lang/rust/issues/86743)

**Comment by hrydgard** [comment]
- [ ] [`glam-rs` impl From for vector type conversions?](https://github.com/bitshifter/glam-rs/issues/220)

**Comment by repi** [comment]
- [ ] [`tract` RUSTSEC-2021-0080 advisory from tar dependency](https://github.com/sonos/tract/issues/538)

**Comment by Jake-Shadle** [comment]
- [ ] [`rustc` Static variables are not exported when targeting `wasm32-unknown-unknown`](https://github.com/rust-lang/rust/issues/88092)

**Comment by VZout** [comment]
* [`SPIRV-Cross` SPIR-V's OpCopyMemory can turn into invalid assignments of spvUnsafeArray](https://github.com/KhronosGroup/SPIRV-Cross/issues/1726) 
* [`SPIRV-Cross` Undeclared identifier error related to buffer sizes](https://github.com/KhronosGroup/SPIRV-Cross/issues/1727)

**Comment by repi** [comment]
- https://github.com/bytecodealliance/cap-std/issues/182

**Comment by Jake-Shadle** [comment]
- https://github.com/googleforgames/agones/issues/2252

**Comment by hrydgard** [comment]
- https://github.com/Traverse-Research/rspirv-reflect/issues/18

**Comment by Jake-Shadle** [comment]
- https://github.com/rust-lang/rustup/issues/2855

**Comment by VZout** [comment]
- https://github.com/rust-lang/rust-clippy/issues/7839

**Comment by Jake-Shadle** [comment]
- https://github.com/gyscos/zstd-rs/issues/135
- https://github.com/gtk-rs/gtk3-rs/issues/646
- https://github.com/sonos/tract/issues/565
- https://github.com/nagisa/rust_tracy_client/issues/24
- https://github.com/rustonaut/vec1/issues/24
- https://github.com/hyperium/tonic/issues/802
- https://github.com/tower-rs/tower-http/issues/153
- https://github.com/getsentry/sentry-rust/issues/373
- https://github.com/getsentry/sentry-rust/issues/374
- https://github.com/Lokathor/chlorine/issues/2
- https://github.com/SSheldon/rust-dispatch/issues/18
- https://github.com/Traverse-Research/gpu-allocator/issues/75

**Comment by emilk** [comment]
* https://github.com/tkaitchuck/aHash/issues/103

**Comment by emilk** [comment]
* https://github.com/rust-windowing/winit/issues/2051

**Comment by repi** [comment]
- https://github.com/spacejam/sled/issues/1387

**Comment by hrydgard** [comment]
- https://github.com/bytecodealliance/cap-std/issues/196

**Comment by bnjbvr** [comment]
- https://github.com/wolfpld/tracy/issues/279
- https://github.com/wolfpld/tracy/issues/280

**Comment by bnjbvr** [comment]
- https://github.com/bytecodealliance/wasmtime/issues/3513

**Comment by hrydgard** [comment]
- https://github.com/rust-windowing/android-ndk-rs/issues/193

**Comment by repi** [comment]
- https://github.com/deps-rs/deps.rs/issues/125

**Comment by bnjbvr** [comment]
- https://github.com/rust-lang/rust/issues/91128

**Comment by bnjbvr** [comment]
- https://github.com/Nercury/android_logger-rs/issues/45

**Comment by khyperia** [comment]
- https://github.com/rust-lang/rust-clippy/issues/8050

**Comment by emilk** [comment]
* https://github.com/notify-rs/notify/issues/374

**Comment by maxded** [comment]
* https://github.com/purpleprotocol/mimalloc_rust/pull/74

**Comment by repi** [comment]
- https://github.com/Lokathor/bytemuck/issues/84

**Comment by bnjbvr** [comment]
- https://github.com/bytecodealliance/wasmtime/issues/3656

**Comment by repi** [comment]
- https://github.com/WebAssembly/wabt/issues/1803

**Comment by repi** [comment]
- https://github.com/rust-lang/rust-clippy/issues/8293

**Comment by bnjbvr** [comment]
- https://github.com/intel/ittapi/issues/38

**Comment by repi** [comment]
- https://github.com/gwihlidal/meshopt-rs/issues/25

**Comment by repi** [comment]
- https://github.com/PolyMeilex/rfd/issues/49

**Comment by Jake-Shadle** [comment]
- - https://github.com/rust-lang/rust/issues/93372

**Comment by bnjbvr** [comment]
- https://github.com/tokio-rs/tracing/issues/1884

**Comment by VZout** [comment]
* https://github.com/RustAudio/cpal/issues/637
* [ ] [Make `stdweb` a optional dependency](https://gitlab.com/gilrs-project/gilrs/-/issues/117)

**Comment by repi** [comment]
- https://github.com/image-rs/image-png/issues/331

**Comment by Jake-Shadle** [comment]
- https://github.com/microsoft/windows-rs/issues/1538

**Comment by Jake-Shadle** [comment]
- https://github.com/nextest-rs/nextest/issues/57

**Comment by Jake-Shadle** [comment]
- https://github.com/shepmaster/twox-hash/issues/85
- https://github.com/LuoZijun/rust-core-video-sys/issues/24

**Comment by repi** [comment]
- https://github.com/rust-lang/rust-clippy/issues/8567

**Comment by Jake-Shadle** [comment]
- https://github.com/microsoft/win32metadata/issues/845

**Comment by repi** [comment]
- https://github.com/rust-windowing/winit/issues/2224

**Comment by Jake-Shadle** [comment]
- https://github.com/rust-lang/rust-clippy/issues/8679

**Comment by Jake-Shadle** [comment]
- https://github.com/rust-lang/rust-clippy/issues/8681

**Comment by repi** [comment]
- https://github.com/johannesvollmer/exrs/issues/151

**Comment by repi** [comment]
- https://github.com/rust-lang/rustfmt/issues/5323

**Comment by Jake-Shadle** [comment]
- https://github.com/microsoft/windows-rs/issues/1720

**Comment by repi** [comment]
- https://github.com/crate-ci/typos/issues/481

**Comment by Hoodad** [comment]
* [ ]  [Add support for selecting sound output device based on `device_type`](https://github.com/RustAudio/cpal/issues/666)

**Comment by Hoodad** [comment]
- https://github.com/rust-windowing/winit/issues/2305

**Comment by maxded** [comment]
- https://github.com/RustAudio/cpal/issues/676

**Comment by Jake-Shadle** [comment]
- https://github.com/rust-lang/rust/issues/99596

**Comment by repi** [comment]
- https://github.com/cberner/redb/issues/300

**Comment by repi** [comment]
- https://github.com/bytecodealliance/cap-std/issues/270

**Comment by fredr** [comment]
- https://github.com/tokio-rs/tracing/issues/2265

**Comment by fu5ha** [comment]
-[ ] https://github.com/rust-windowing/winit/issues/2387

**Comment by repi** [comment]
- https://github.com/Enselic/cargo-public-api/issues/100

**Comment by repi** [comment]
- https://github.com/nabijaczleweli/cargo-update/issues/190

**Comment by TimonPost** [comment]
https://github.com/metrics-rs/metrics/pull/285

**Comment by jnises** [comment]
https://github.com/Enselic/cargo-public-api/issues/143

**Comment by repi** [comment]
- https://github.com/Enselic/cargo-public-api/issues/145

**Comment by repi** [comment]
- https://github.com/sonos/tract/issues/810

**Comment by repi** [comment]
- https://github.com/Enselic/cargo-public-api/issues/163

**Comment by repi** [comment]
- https://github.com/clap-rs/clap/issues/4279

**Comment by Jake-Shadle** [comment]
- https://github.com/rust-lang/cargo/issues/11319

**Comment by Jake-Shadle** [comment]
- https://github.com/mozilla/sccache/issues/1437

**Comment by TimonPost** [comment]
https://github.com/jacobsky/egui-stylist/pulls

**Comment by Jake-Shadle** [comment]
- https://github.com/rust-lang/rust/issues/107350

**Comment by bnjbvr** [comment]
- https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/614 lol

**Comment by davidpdrsn** [comment]
- https://github.com/dtolnay/syn/issues/1378

**Comment by TimonPost** [comment]
https://github.com/rust-windowing/winit/issues/2695

**Comment by TimonPost** [comment]
- https://github.com/EmbarkStudios/rust-ecosystem/issues/36

**Comment by repi** [comment]
- https://github.com/metrics-rs/metrics/issues/346

**Comment by TimonPost** [comment]
- https://github.com/rust-windowing/winit/issues/2752

**Comment by repi** [comment]
- https://github.com/bytecodealliance/wasm-tools/issues/1013

**Comment by repi** [comment]
- https://github.com/tokio-rs/tracing/issues/2587

**Comment by rib** [comment]
https://github.com/bbqsrc/cargo-ndk/issues/104

**Comment by repi** [comment]
- https://github.com/bytecodealliance/wasmtime/issues/6433

**Comment by repi** [comment]
- https://github.com/mozilla/cargo-vet/issues/481

**Comment by TimonPost** [comment]
- https://github.com/bytecodealliance/wasmtime/issues/6541

**Comment by repi** [comment]
- https://github.com/Seeker14491/opener/issues/26

**Comment by rib** [comment]
- https://github.com/rust-lang/rust/issues/112461

**Comment by repi** [comment]
- https://github.com/benashford/redis-async-rs/issues/87

**Comment by Jake-Shadle** [comment]
- https://github.com/Byron/gitoxide/issues/923

**Comment by TimonPost** [comment]
- https://github.com/bytecodealliance/wasmtime/issues/6798

**Comment by repi** [comment]
- https://github.com/davidlattimore/cackle/issues/3

**Comment by repi** [comment]
- https://github.com/illicitonion/num_enum/issues/129

**Comment by TimonPost** [comment]
- https://github.com/emilk/egui/issues/1250

**Comment by TimonPost** [comment]
- https://github.com/bytecodealliance/wasmtime/issues/6889

**Comment by repi** [comment]
- https://github.com/PolyMeilex/rfd/issues/139

**Comment by repi** [comment]
- https://github.com/gyscos/zstd-rs/issues/242

**Comment by fu5ha** [comment]
- https://github.com/phaazon/splines/pull/98

**Comment by repi** [comment]
- [ ] https://gitlab.com/gilrs-project/gilrs/-/issues/149

**Comment by repi** [comment]
- https://github.com/autometrics-dev/autometrics-rs/issues/155

**Comment by repi** [comment]
- https://github.com/ash-rs/ash/issues/814

**Comment by repi** [comment]
- https://github.com/hyperium/tonic/issues/1183
- https://github.com/hyperium/h2/issues/636
