### ISSUE TITLE
RLS in VS Code robustness & performance

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-ecosystem#8]
We use a single large workspace and monorepo and RLS very often hangs / stops working. 

Also performance with having RLS build our repo for its own target can be quite bad, esp. working on laptop. Looking forward to future more incremental background service.

Related issues:
- [ ] [clippy: force full re-clippy #2604](https://github.com/rust-lang/rust-clippy/issues/2604)
- [ ] [rls: Performance issue of rls on large code base](https://github.com/rust-lang/rls/issues/1410)
- [ ] [rust gamedev wg: RLS for huge projects](https://github.com/rust-gamedev/wg/issues/22)

**Comment by repi** [comment]
Another problem we have with RLS is that we have large C++ dependencies built in their `build.rs` files and these will be built in RLS for no use and causing RLS to be inactive building for 5-10 minutes on a laptop. Our [`physx`](https://github.com/EmbarkStudios/physx-rs)  and [`ash-molten`](https://github.com/EmbarkStudios/ash-molten) are examples of such crates.

Would want in `build.rs` to skip these heavy builds if building for RLS, or something similar.

Found a related issue here: https://github.com/rust-lang/cargo/issues/6834

**Comment by nox** [comment]
As a workaround for RLS, you can do this:

```rust
    // Stop here if caller is RLS.
    let cargo = env::var_os("CARGO").unwrap();
    let output = Command::new(cargo).arg("--version").output().unwrap();
    if output.stdout.starts_with(b"rls ") {
        return;
    }
```

This doesn't help for `cargo check` though.

**Comment by rlabrecque** [comment]
My workspace isn't even large, 3 cargo crates in the workspace, ~200 LOC each, `tonic`, `clap`, `r2d2-postgres`, `tracing` based. Compiling on a laptop, RLS needs to be restarted at least hourly.

**Comment by repi** [comment]
Closing this as rust-analyzer a few months ago got good enough for us to switch over to it at Embark! It does have some issues (that we should file and track) but will be our primary focus going forward
